---
- hosts: "{{ HOSTS | default('satellite.example.com') }}"
  become: true
  vars:
    disconnected_mode: "true"
  tasks:
    - name: disconnected mode on ==> "{{ disconnected_mode }}"
      command: >-
        hammer settings set --name content_disconnected --value {{ disconnected_mode }}
      register: hammer_disconnect
      ignore_errors: true

    - name: hammer disconnected mode switch output 
      debug:
        msg: "{{ hammer_disconnect }}"
