---
- hosts: "{{ HOSTS | default('control[0]') }}"
  connection: local
  vars:
    controller_infra_workloads:
      - redhat_cop.controller_configuration.projects
      - redhat_cop.controller_configuration.inventories
      - redhat_cop.controller_configuration.inventory_sources
      - redhat_cop.controller_configuration.job_templates
    controller_hostname: "{{ lookup('env', 'TOWER_HOST') }}"
    #controller_hostname: "{{ hostvars[inventory_hostname].ansible_fqdn }}"
    controller_validate_certs: false

  tasks:
    - name: Slurp dynamic_development_source_vars.yaml
      slurp: src=files/dynamic_development_source_vars.yaml
      register: dynamic_development_source_vars_slurped

    - set_fact:
        dynamic_development_source_vars: "{{ dynamic_development_source_vars_slurped['content'] | b64decode }}"

    # Gather EC2 metadata facts
    - amazon.aws.ec2_metadata_facts:
  
    - set_fact:
        workshop_ec2_region: "{{ ansible_ec2_instance_identity_document_region }}"

    - debug:
        msg: "{{ dynamic_development_source_vars }}"   
    - name: deploy controller_infra workloads
      include_role:
        name: "{{ controller_infra_vars }}"
      loop: "{{ controller_infra_workloads }}"
      loop_control:
        loop_var: controller_infra_vars
    - name: Log Demo
      ansible.builtin.uri:
        url: https://docs.google.com/forms/d/e/1FAIpQLSdIZ77YpETjEfGOoYlXtMnQiU-6M7QFlb2hJA4ujo25QYb2jw/formResponse
        method: POST
        body: "ifq&entry.1569353616=satellite &entry.498055740={{ lookup('ansible.builtin.env', 'AWX_HOST') }}&sumbit=Submit"
      ignore_errors: true
