---
foreman_content_views:
  # Red Hat Enterprise Linux 7
  - name: RHEL7
    content_view: RHEL7
    content_view_update: true
    lifecycle_environments:
      - "RHEL7_Dev"
      - "RHEL7_Test"
      - "RHEL7_Prod"
    repos:
    - name: Red Hat Enterprise Linux 7 Server (RPMs)
      basearch: x86_64
      releasever: 7Server
      product: 'Red Hat Enterprise Linux Server'
    - name: Red Hat Enterprise Linux 7 Server - Extras (RPMs)
      basearch: x86_64
      product: 'Red Hat Enterprise Linux Server'
    - name: Red Hat Satellite Utils 6.11 (for RHEL 7 Server) (RPMs)
      basearch: x86_64
      product: 'Red Hat Enterprise Linux Server'
  - name: RHEL8
    content_view: RHEL8
    content_view_update: true
    lifecycle_environments:
      - "RHEL8_Dev"
      - "RHEL8_Test"
      - "RHEL8_Prod"
    repos:
    - name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
      releasever: 8
      product: Red Hat Enterprise Linux for x86_64
    - name: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
      releasever: 8
      product: Red Hat Enterprise Linux for x86_64
    - name: Red Hat Satellite Utils 6.11 for RHEL 8 x86_64 (RPMs)
      product: Red Hat Enterprise Linux for x86_64
