---
lifecycle_environments:
  # Red Hat Enterprise Linux 7
  - name: "RHEL7_Dev"
    prior: "Library"
  - name: "RHEL7_QA"
    prior: "RHEL7_Dev"
  - name: "RHEL7_Prod"
    prior: "RHEL7_QA"
  # Red Hat Enterprise Linux 8
  - name: "RHEL8_Dev"
    prior: "Library"
  - name: "RHEL8_QA"
    prior: "RHEL8_Dev"
  - name: "RHEL8_Prod"
    prior: "RHEL8_QA"
  # Community Enterprise Linux 7
  - name: "CentOS7_Dev"
    prior: "Library"
  - name: "CentOS7_QA"
    prior: "CentOS7_Dev"
  - name: "CentOS7_Prod"
    prior: "CentOS7_QA"
  # Community Enterprise Linux 8
  - name: "CentOS8_Dev"
    prior: "Library"
  - name: "CentOS8_QA"
    prior: "CentOS8_Dev"
  - name: "CentOS8_Prod"
    prior: "CentOS8_QA"
