---
- hosts: all
  gather_facts: false
  tasks:
  - name: Debug hostvars - satellite.example.com
    debug:
      msg: "{{ hostvars['satellite.example.com'] }}"

  - name: Debug Content View filter - RHEL
    debug:
      msg: "{{ hostvars['satellite.example.com']['foreman_content_views'] | selectattr('name', 'match', '^RHEL.*$') | list}}"
